import Head from 'next/head'
import Image from 'next/image'
import Header from '../src/components/header'
import styles from '../styles/Home.module.css'
import Card from '../src/components/card'
import Main from '../src/components/main'
import proto01 from '../OMG/01.jpg'


export default function Home() {
  


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}> 
      <Header image={"aqui"} />
      <section>
      <Main />
      <Card color={true} />
      <Card color={true} />
      <Card color={true} />
      <Card color={true} />
      <Card color={true} />
      <Card color={true} />
      </section>
      </div>
    </>
    )
}
